// redux/actions/actionTypes.js
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_CHAT_ROOM_ID = 'SET_CHAT_ROOM_ID';
export const SET_MESSAGES = 'SET_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGE_LOCALLY = 'DELETE_MESSAGE_LOCALLY';
export const ADD_LOCALLY_DELETED_MESSAGE_ID = 'ADD_LOCALLY_DELETED_MESSAGE_ID';
export const UPDATE_USER_DATA_GALLERY_IMAGES = 'UPDATE_USER_DATA_GALLERY_IMAGES';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';
export const SET_BLOCKED_USERS = 'SET_BLOCKED_USERS';
export const FILTER_MESSAGES = 'FILTER_MESSAGES';




